config/routes.rb
Myblog::Application.routes.draw do
  resources :posts

  resources :robots

  resources :messages do
    get :finish_queue, on: :member
  end

  resources :blogs
  root to: 'books#index'
  get 'books/openlink', controller: 'books'
  get '/home', to: 'pages#home'
  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

end

app/models/message.rb
#!/bin/env ruby  
# encoding: utf-8
class Message < ActiveRecord::Base
  attr_accessible :Content, :CreateTime, :FromUserName, :FuncFlag, :MsgType, :ToUserName, :Status

  def subStr1
    "<xml>
    <ToUserName>#{self.FromUserName}</ToUserName>
    <FromUserName>#{self.ToUserName}</FromUserName>
    <CreateTime>#{self.CreateTime}</CreateTime>
    <MsgType>#{self.MsgType}</MsgType>
    <Content>"
  end

  def subStr2
    "</Content>
    <FuncFlag>0</FuncFlag>
    </xml>"
  end

  def frontPeopleNum
    Message.where("Status = ? AND created_at < ?", true, self.created_at).count
  end

  def rearPeopleNum
    Message.where("Status = ? AND created_at > ?", true, self.created_at).count
  end

  def averageWaitTime
    # 查询近2个小时以内的，并且排在队列第一个的平均等待时间
    # 
    messages = Message.where("Status = ? AND created_at > ?", false, 2.hour.ago)
    if messages != []
      t = 0
      messages.each do |me|
        t = me.updated_at - me.created_at
      end
      return t / messages.count
    end
    return 0
  end

  def waitTime
    return "您可以准备进入餐馆了" if frontPeopleNum < 1
    "大约还需要等待#{(averageWaitTime.to_i/60) * frontPeopleNum}分钟"
  end

  def returnQueueStatus
    subStr1 + "微信排队\n\n
    欢迎来到：江滨路首府甲第大酒店\n
    现在时间是：#{Time.zone.now.strftime("%Y-%m-%d %H:%M:%S")}\n\n
    您的号码是：#{self.id}\n
    在你前面有#{frontPeopleNum}位客人。\n" + waitTime + subStr2
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  http_basic_authenticate_with name: "gonjay", password: "gon_jay"

  def index
    @messages = Message.where("Status = ?", true)
  end

  def new
    @me = Message.new()
  end

  def finish_queue
    @me = Message.find(params[:id])
    @me.Status = false
    @me.updated_at = Time.now
    @me.save
    redirect_to :back
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<div class="mycontainer">
	<table class="table">
		<tr>Messages</tr>
		<tr>

			<th>UserName</th>
			<th>Content</th>
			<th class="hidden-phone">CreateTime</th>
			<th class="hidden-phone">FuncFlag</th>
			<th class="hidden-phone">MsgType</th>
			<th class="hidden-phone">ToUserName</th>
			<th>控制</th>

		</tr>
		<% @messages.each do |me| %>
		<tr>
			<td><%= me.FromUserName %></td>
			<td><%= me.Content %></td>
			<td class="hidden-phone"><%= me.CreateTime %></td>
			<td class="hidden-phone"><%= me.FuncFlag %></td>
			<td class="hidden-phone"><%= me.MsgType %></td>
			<td class="hidden-phone"><%= me.ToUserName %></td>
			<td>
				<%= link_to "完成", finish_queue_message_path(me), class:"btn"  %>
			</td>

			<% end %>
		</tr>
	</table>
</div>

app/views/messages/new.html.erb
<form accept-charset="UTF-8" action="/robots" class="new_message" id="new_message" method="post">
	<div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓">
		<input name="authenticity_token" type="hidden" value="+OMh+x+vk7VWMWyztio9vHx7hv73K8k1RKJ2fxwqLuM=">
	</div>

	<label for="message_FromUserName">Fromusername</label>
	<input id="message_FromUserName" name="xml[FromUserName]" size="30" type="text">

	<label for="message_FromUserName">ToUserName</label>
	<input id="message_FromUserName" name="xml[ToUserName]" size="30" type="text">

	<label for="message_FromUserName">Content</label>
	<input id="message_FromUserName" name="xml[Content]" size="30" type="text">

	<label for="message_FromUserName">MsgType</label>
	<input id="message_FromUserName" name="xml[MsgType]" size="30" type="text">	

	<input name="commit" type="submit" value="Create Message">
</form>