config/routes.rb
Myblog::Application.routes.draw do
  resources :posts

  resources :robots

  resources :messages do
    get :finish_queue, on: :member
  end

  resources :blogs
  root to: 'books#index'
  get 'books/openlink', controller: 'books'
  get '/home', to: 'pages#home'
  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

end

app/models/book.rb
#!/bin/env ruby  
# encoding: utf-8  
require 'open-uri'

class Book < ActiveRecord::Base
  attr_accessible :name
  attr_accessor :index_number, :status, :img_src, :id_code, :auther, :publisher

  def search_index(params)
    @url = 'http://202.114.181.3:8080/opac/openlink.php?' +
     'strText=' + params[:strText].to_s + 
     '&strSearchType=' + params[:strSearchType].to_s + 
     '&match_flag=' + params[:match_flag].to_s + 
     '&historyCount=' + params[:historyCount].to_s +
     '&doctype=' + params[:doctype].to_s + 
     '&displaypg=' + params[:displaypg].to_s+ 
     '&showmode=' + params[:showmode].to_s+ 
     '&sort=' + params[:sort].to_s+ 
     '&orderby=' + params[:orderby].to_s+ 
     '&location=' + params[:location].to_s

     html = open(URI.escape(@url)).read
     doc = Nokogiri::HTML(html)
     @books = []

     doc.css('.book_article')[3].css('.book_list_info').each do |item|
      @book = Book.new
      @book.img_src = item.css('img')[0]['src']
      @book.id_code = item.css('h3')[0].css('a')[0]['href']
      @book.name = item.css('h3')[0].css('a')[0].content
      @book.index_number = item.css('h3')[0].css('span')[0].content + item.css('h3')[0].content.split("#{@book.name}")[1]
      @book.status = item.css('p')[0].css('span')[0].content
      p_content = item.css('p')[0].content.split("#{@book.status}")[1]
      if p_content.include?(".")
        p = p_content.split(".")
        @book.auther = p[0]
        @book.publisher = p[1]
      else
        p = p_content.split("著")
        @book.auther = p[0]
        @book.publisher = p[1]
      end
      @books << @book
     end

     @books
    
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index

  end

  def openlink
    @content = Book.new.search_index(params)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @content }
    end
  end
end

app/views/books/index.html.erb
<%= render 'layouts/header' %>
<div class="mycontainer">
	<h1 style="text-align: center;">湖北工业大学<br>图书搜索</h1>
	<form action="<%= books_openlink_path %>" method="get" name="f" onsubmit="return chkForm(this)" id="f">    
		<input style=";" type="text" size="45" name="strText" id="strText" value="">
		<div style="margin-bottom: 10px">
			<input type="submit" class="btn btn-primary" value=" 检 索 " size="30">
			<input type="button" id="btnShowMore" onclick="showMore()" class="btn btn-success" value="更多限制" size="30">
		</div>
		<div class="search_bgimg"><select class="option" name="strSearchType" size="1" style="width:100px;">
			<option value="title">题&nbsp;&nbsp;名</option>
			<option value="author">责任者</option>
			<option value="keyword">主题词</option>
			<option value="isbn">ISBN/ISSN</option>
			<option value="asordno">订购号</option>
			<option value="coden">分类号</option>
			<option value="callno">索书号</option>
			<option value="publisher">出版社</option>
			<option value="series">丛书名</option>
			<option value="tpinyin">题名拼音</option>
			<option value="apinyin">责任者拼音</option>
		</select>
		<select class="option" name="match_flag" size="1" style="width:100px;">
			<option value="forward">前方一致</option>
			<option value="full">完全匹配</option>
			<option value="any">任意匹配</option>
		</select>
		<input type="hidden" id="historyCount" name="historyCount" value="1">

		
		<br>
		<p><input type="radio" name="doctype" value="ALL" checked="checked">
			所有书刊
			<input type="radio" name="doctype" value="01">
			中文图书
			<input type="radio" name="doctype" value="02">
			西文图书
			<input type="radio" name="doctype" value="11">
			中文期刊
			<input type="radio" name="doctype" value="12">
			西文期刊　　　
		</p>
		<div id="child1" class="childl" style="display: none;">
			<p><strong>显示方式：</strong><select class="option" name="displaypg" size="1" style="width:100px;">
				<option value="20">20条</option>
				<option value="30">30条</option>
				<option value="50">50条</option>
				<option value="100">100条</option>
			</select>    
			<input type="radio" name="showmode" value="list" checked="checked">
			详细显示
			<input type="radio" name="showmode" value="table">
			表格显示</p>
			<p><strong>排序方式：</strong><select class="option" name="sort" size="1" style="width:100px;">
				<option value="CATA_DATE">入藏日期</option>
				<option value="M_TITLE">题&nbsp;&nbsp;名</option>
				<option value="M_AUTHOR">责任者</option>
				<option value="M_CALL_NO">索书号</option>
				<option value="M_PUBLISHER">出版社</option>
				<option value="M_PUB_YEAR">出版日期</option>
			</select>
			<input type="radio" name="orderby" value="asc">
			升序排列
			<input type="radio" name="orderby" value="desc" checked="checked">
			降序排列</p>
			<p><strong>检索范围：</strong><select class="option" id="location" name="location" size="1" style="width:100px;">
				<option value="ALL">所有馆藏地</option>
				<option value="00011">外文书库（工2-C座西大厅）</option>
				<option value="00020">普通阅览室（工2-C座西大厅）</option>
				<option value="00021">参考阅览室（本馆4楼）</option>
				<option value="00023">中文现刊室（本馆2楼）</option>
				<option value="00024">中文过刊室</option>
				<option value="00025">外文期刊室</option>
				<option value="00026">艺术建筑阅览室（本馆4楼）</option>
				<option value="sksk ">社会科学书库（本馆5楼）</option>
				<option value="xsk  ">新书库（本馆1楼）</option>
				<option value="zhyls">综合阅览室（工2-C座西厅）</option>
				<option value="zksk ">自然科学书库（本馆3楼）</option>
			</select>
		</p>
	</form>
	<footer><h4>MothinLab牛逼出品</h4></footer>
</div>

<script type="text/javascript">
function showMore(){
	$('#child1').toggle();
}
</script>

app/views/books/openlink.html.erb
<%= render 'layouts/header' %>
<div class='row'>
	<% @content.each do |book| %>
	<div class='span4 card'>
		<!-- <div class="row"> -->
		<!-- <div class="myspan2"> -->
			<%= image_tag(book.img_src, :size => "150x290" )%>
		<!-- </div> -->
		<div class="span4">
			<h4><%= link_to book.name, 'http://202.114.181.3:8080/opac/' + book.id_code %></h4>
			<p><%= book.auther %></p>
			<p><%= book.publisher %></p>
			<p><%= book.index_number %></p>
			<p><%= book.status %></p>
		</div>
		<!-- </div> -->
	</div>
	<% end %>
</div>